version: "2"
linters:
  default: all
  disable:
    - "errcheck"  # I appreciate the intent, but I'm not checking errors on fmt.Printf etc.
    - "forbidigo"  # fmt.Print* are fine for now
    - "funlen"  # We have inherited lots of long lines
    - "gochecknoglobals"  # One day there will be no globals but I do not expect it will be today
    - "godot"  # Implicit full stops are ok
    - "godox"  # There will be TODOs
    - "lll"  # We have inherited lots of long lines
    - "mnd"  # I do not like magic numbers, but there are plenty inherited from upstream, so let's roll with them for now
    - "nlreturn"  # Lots of false positives on C code that isn't a return
    - "paralleltest"  # One day, but let's have *working* tests first
    - "prealloc"  # One day, but not now
    - "testpackage"  # Noble intent, but right now we're doing all sorts of juggling with packages, so let's save this for later
    - "varnamelen"  # Noble intent, but we're inheriting lots of short variable names, and I'd like to stay close to upstream at first
    - "wrapcheck"  # Error wrapping is the least of my concerns
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: invalid
              desc: Dummy deny because we need a non-empty list
    gocritic:
      disabled-checks:
        - dupSubExpr  # Too many false positives on cgo code
    revive:
      rules:
        - name: "var-naming"
          disabled: true  # There's going to be assorted naming conventions inherited from the original C for a while
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
  exclusions:
    warn-unused: true
