version: "2"
linters:
  default: all
  disable:
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: invalid
              desc: Dummy deny because we need a non-empty list
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    warn-unused: true
