version = 1

[[annotations]]
path = [
	"conf/**",
	"data/**",
	"man/**",
]
SPDX-FileCopyrightText = "The Dire Wolf Authors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [
	"*.md",
	".claude/**",
	".git*",
	".github/**",
	".golangci.yml",
	"Makefile",
	"cmd/**",
	"docs/**",
	"internal/**",
	"go.mod",
	"go.sum",
	"src/*.go",
	"test-scripts/**",
	"upstream-tracker/**",
]
SPDX-FileCopyrightText = "The Samoyed Authors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "debian/**"
SPDX-FileCopyrightText = "(C) 2014 Iain R. Learmonth <irl@fsfe.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"
