// SPDX-FileCopyrightText: The Samoyed Authors
// SPDX-License-Identifier: AGPL-3.0-or-later

//nolint:gochecknoglobals
package mheard

// KG 2026-03-07 These tests were generated by Claude based on mheard.go
// and as such it's very much a test of the implementation as-is.
// A failing test may thus be a problem with the test itself rather than any future changes...

import (
	"testing"
	"time"

	"github.com/doismellburning/samoyed/internal/ax25"
	"github.com/doismellburning/samoyed/internal/maybe"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- age ---

func TestAge(t *testing.T) {
	var now = time.Now()

	t.Run("zero time returns placeholder", func(t *testing.T) {
		assert.Equal(t, "-", age(now, time.Time{}))
	})

	t.Run("90 minutes ago", func(t *testing.T) {
		assert.Equal(t, "1:30", age(now, now.Add(-90*time.Minute)))
	})

	t.Run("5 minutes ago", func(t *testing.T) {
		assert.Equal(t, "0:05", age(now, now.Add(-5*time.Minute)))
	})

	t.Run("same moment", func(t *testing.T) {
		assert.Equal(t, "0:00", age(now, now))
	})
}

// --- latLon ---

func TestLatLon(t *testing.T) {
	t.Run("both unknown", func(t *testing.T) {
		assert.Equal(t, "-", latLon(maybe.Nothing[float64](), maybe.Nothing[float64]()))
	})

	t.Run("lat unknown lon known", func(t *testing.T) {
		assert.Equal(t, "-", latLon(maybe.Nothing[float64](), maybe.Just(-71.0)))
	})

	t.Run("lat known lon unknown", func(t *testing.T) {
		assert.Equal(t, "-", latLon(maybe.Just(42.0), maybe.Nothing[float64]()))
	})

	t.Run("both known", func(t *testing.T) {
		assert.Equal(t, "42.36 -71.06", latLon(maybe.Just(42.36), maybe.Just(-71.06)))
	})
}

// --- New ---

func TestNew(t *testing.T) {
	var mdb = New(3)
	require.NotNil(t, mdb)
	assert.Equal(t, 3, mdb.debug)
	assert.NotNil(t, mdb.db)
	assert.Empty(t, mdb.db)
}

// --- Count ---

func TestDBCount(t *testing.T) {
	var now = time.Now()

	t.Run("empty db", func(t *testing.T) {
		var mdb = New(0)
		assert.Equal(t, 0, mdb.Count(0, 60))
	})

	t.Run("station heard directly counted", func(t *testing.T) {
		var mdb = New(0)
		mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
			callsign:    "W1AW",
			lastHeardRF: now.Add(-10 * time.Minute),
			numDigiHops: 0,
		}
		assert.Equal(t, 1, mdb.Count(0, 60))
	})

	t.Run("station excluded by max hops", func(t *testing.T) {
		var mdb = New(0)
		mdb.db["W2AW"] = &station{ //nolint:exhaustruct_v5
			callsign:    "W2AW",
			lastHeardRF: now.Add(-5 * time.Minute),
			numDigiHops: 3,
		}
		assert.Equal(t, 0, mdb.Count(2, 60))
	})

	t.Run("IS-only station not counted", func(t *testing.T) {
		var mdb = New(0)
		mdb.db["IS1"] = &station{ //nolint:exhaustruct_v5
			callsign:    "IS1",
			lastHeardIS: now.Add(-5 * time.Minute),
		}
		assert.Equal(t, 0, mdb.Count(8, 60))
	})

	t.Run("old RF station excluded by time limit", func(t *testing.T) {
		var mdb = New(0)
		mdb.db["OLD"] = &station{ //nolint:exhaustruct_v5
			callsign:    "OLD",
			lastHeardRF: now.Add(-120 * time.Minute),
			numDigiHops: 0,
		}
		assert.Equal(t, 0, mdb.Count(0, 60))
	})

	t.Run("multiple stations counted correctly", func(t *testing.T) {
		var mdb = New(0)
		mdb.db["A"] = &station{lastHeardRF: now.Add(-5 * time.Minute), numDigiHops: 0}  //nolint:exhaustruct_v5
		mdb.db["B"] = &station{lastHeardRF: now.Add(-10 * time.Minute), numDigiHops: 1} //nolint:exhaustruct_v5
		mdb.db["C"] = &station{lastHeardRF: now.Add(-10 * time.Minute), numDigiHops: 3} //nolint:exhaustruct_v5
		mdb.db["D"] = &station{lastHeardIS: now.Add(-5 * time.Minute)}                  //nolint:exhaustruct_v5
		assert.Equal(t, 2, mdb.Count(2, 60))
	})

	t.Run("debug mode prints message", func(t *testing.T) {
		var mdb = New(1)
		mdb.db["X"] = &station{lastHeardRF: now.Add(-5 * time.Minute), numDigiHops: 0} //nolint:exhaustruct_v5
		assert.Equal(t, 1, mdb.Count(0, 60))
	})
}

// --- SaveRF helpers ---

var saveRFNoLat, saveRFNoLon = maybe.Nothing[float64](), maybe.Nothing[float64]()

// --- SaveRF ---

func TestDBSaveRFNewStation(t *testing.T) {
	var mdb = New(0)
	var pp = ax25.FromText("W1AW>APRS:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)

	require.Contains(t, mdb.db, "W1AW")
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.Equal(t, 0, mdb.db["W1AW"].numDigiHops)
	assert.Equal(t, 0, mdb.db["W1AW"].channel)
	assert.Equal(t, maybe.Nothing[float64](), mdb.db["W1AW"].dlat)
	assert.Equal(t, maybe.Nothing[float64](), mdb.db["W1AW"].dlon)
}

func TestDBSaveRFPositionSaved(t *testing.T) {
	var mdb = New(0)
	var pp = ax25.FromText("W1AW>APRS:test", true)

	mdb.SaveRF(0, pp, maybe.Just(42.36), maybe.Just(-71.06))

	require.Contains(t, mdb.db, "W1AW")
	assert.Equal(t, maybe.Just(42.36), mdb.db["W1AW"].dlat)
	assert.Equal(t, maybe.Just(-71.06), mdb.db["W1AW"].dlon)
}

func TestDBSaveRFPositionNotSavedForNonPositionPacket(t *testing.T) {
	var mdb = New(0)
	var pp = ax25.FromText("W1AW>APRS:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)

	assert.Equal(t, maybe.Nothing[float64](), mdb.db["W1AW"].dlat)
}

func TestDBSaveRFUnknownPositionNotSaved(t *testing.T) {
	var mdb = New(0)
	var pp = ax25.FromText("W1AW>APRS:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)

	assert.Equal(t, maybe.Nothing[float64](), mdb.db["W1AW"].dlat)
}

func TestDBSaveRFExistingStationUpdated(t *testing.T) {
	var mdb = New(0)
	var pp = ax25.FromText("W1AW>APRS:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
	// Push the last-heard time back so the 15-second same-transmission guard doesn't fire.
	mdb.db["W1AW"].lastHeardRF = time.Now().Add(-30 * time.Second)
	mdb.SaveRF(1, pp, saveRFNoLat, saveRFNoLon)

	assert.Equal(t, 2, mdb.db["W1AW"].count)
	assert.Equal(t, 1, mdb.db["W1AW"].channel)
}

func TestDBSaveRFHigherHopSkippedWithin15s(t *testing.T) {
	var mdb = New(0)

	// First: heard directly (0 hops).
	var ppDirect = ax25.FromText("W1AW>APRS:test", true)
	mdb.SaveRF(0, ppDirect, saveRFNoLat, saveRFNoLon)
	assert.Equal(t, 0, mdb.db["W1AW"].numDigiHops)

	// Second: heard via one digipeater, but within 15 seconds of the first.
	var ppVia = ax25.FromText("W1AW>APRS,RELAY*:test", true)
	mdb.SaveRF(0, ppVia, saveRFNoLat, saveRFNoLon)

	// Should stay at 1 count and 0 hops (the higher-hop copy is ignored).
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.Equal(t, 0, mdb.db["W1AW"].numDigiHops)
}

func TestDBSaveRFWideHopHackReducesCount(t *testing.T) {
	var mdb = New(0)
	// W3AW* (used, len 4 – not WIDE) then WIDE2* (used, len 5, WIDE prefix, ssid 0).
	// Raw hops = 2, hack reduces by one → hops = 1.
	var pp = ax25.FromText("W1AW>APRS,W3AW*,WIDE2*:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)

	assert.Equal(t, 1, mdb.db["W1AW"].numDigiHops)
}

func TestDBSaveRFWideHackIgnoresNonZeroSsid(t *testing.T) {
	var mdb = New(0)
	// WIDE1-1 has ssid 1, so the hack must not fire.
	// Raw hops = 2 and nothing should be reduced.
	var pp = ax25.FromText("W1AW>APRS,W3AW*,WIDE1-1*:test", true)

	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)

	assert.Equal(t, 2, mdb.db["W1AW"].numDigiHops)
}

func TestDBSaveRFDebug1SkipBranch(t *testing.T) {
	// debug=1 + higher-hop copy within 15 s → exercises the "skip" debug message.
	var mdb = New(1)
	var ppDirect = ax25.FromText("W1AW>APRS:test", true)
	mdb.SaveRF(0, ppDirect, saveRFNoLat, saveRFNoLon)

	var ppVia = ax25.FromText("W1AW>APRS,RELAY*:test", true)
	mdb.SaveRF(0, ppVia, saveRFNoLat, saveRFNoLon)
}

func TestDBSaveRFDebug1UpdateBranch(t *testing.T) {
	// debug=1 + update after >15 s → exercises the "update time" debug message.
	var mdb = New(1)
	var pp = ax25.FromText("W1AW>APRS:test", true)
	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
	mdb.db["W1AW"].lastHeardRF = time.Now().Add(-30 * time.Second)
	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
}

func TestDBSaveRFDebug1TriggersDump(t *testing.T) {
	var mdb = New(1)
	var pp = ax25.FromText("W1AW>APRS:test", true)
	// Must not panic; dump is triggered by debug > 0.
	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
}

func TestDBSaveRFDebug2PrintsCountAndDump(t *testing.T) {
	var mdb = New(2)
	var pp = ax25.FromText("W1AW>APRS:test", true)
	// Must not panic; both the count debug line and dump are triggered.
	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
}

// --- dump sort coverage ---

// TestDBDumpSortIsAfterRf calls dump directly with stations whose IS
// timestamp is newer than their RF timestamp, guaranteeing the
// "ta = ma.lastHeardIS" branch inside the sort comparator is reached.
func TestDBDumpSortIsAfterRf(t *testing.T) {
	var mdb = New(0)
	var now = time.Now()

	for i, key := range []string{"AA", "BB", "CC", "DD", "EE"} {
		mdb.db[key] = &station{ //nolint:exhaustruct_v5
			callsign:    key,
			lastHeardRF: now.Add(-time.Duration(60-i*10) * time.Minute),
			lastHeardIS: now.Add(-time.Duration(i*5) * time.Minute),
		}
	}

	mdb.dump()
}

// TestDBDumpSort exercises the sort comparison function inside dump via
// SaveRF with debug=1.  The stations have deliberately varied timestamps so
// that all three comparison outcomes (before / after / equal) are reached.
func TestDBDumpSort(t *testing.T) {
	var mdb = New(1)
	var now = time.Now()
	var sameTime = now.Add(-20 * time.Minute)

	// Two stations with identical effective time → equal comparison (return 0).
	mdb.db["EQ1"] = &station{ //nolint:exhaustruct_v5
		callsign:    "EQ1",
		lastHeardRF: sameTime,
	}
	mdb.db["EQ2"] = &station{ //nolint:exhaustruct_v5
		callsign:    "EQ2",
		lastHeardRF: sameTime,
	}
	// A station whose IS time is more recent than its RF time, exercising the
	// "use IS time" branch inside the comparator.
	mdb.db["ISLATE"] = &station{ //nolint:exhaustruct_v5
		callsign:    "ISLATE",
		lastHeardRF: now.Add(-30 * time.Minute),
		lastHeardIS: now.Add(-5 * time.Minute),
	}
	// An older station to ensure at least one before/after comparison.
	mdb.db["OLD"] = &station{ //nolint:exhaustruct_v5
		callsign:    "OLD",
		lastHeardRF: now.Add(-60 * time.Minute),
	}

	// Trigger dump via SaveRF.
	var pp = ax25.FromText("W1AW>APRS:test", true)
	mdb.SaveRF(0, pp, saveRFNoLat, saveRFNoLon)
}

// --- SaveIS ---

func TestDBSaveISNewStation(t *testing.T) {
	var mdb = New(0)

	mdb.SaveIS("W1AW>APRS,TCPIP*,qAC,T2SERVER:test")

	require.Contains(t, mdb.db, "W1AW")
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.False(t, mdb.db["W1AW"].lastHeardIS.IsZero())
}

func TestDBSaveISExistingStationUpdated(t *testing.T) {
	var mdb = New(0)

	mdb.SaveIS("W1AW>APRS:first")
	mdb.SaveIS("W1AW>APRS:second")

	assert.Equal(t, 2, mdb.db["W1AW"].count)
}

func TestDBSaveISDebug1(t *testing.T) {
	var mdb = New(1)
	// Exercises both the "added new" and "update time" debug paths.
	mdb.SaveIS("W1AW>APRS:test1")
	mdb.SaveIS("W1AW>APRS:test2")
}

func TestDBSaveISDebug2(t *testing.T) {
	var mdb = New(2)
	mdb.SaveIS("W1AW>APRS:test")
}

// --- WasRecentlyNearby ---

func TestDBWasRecentlyNearbyUnknownStation(t *testing.T) {
	var mdb = New(0)
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyISOnlyStation(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardIS: time.Now(),
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyTooLongAgo(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-120 * time.Minute),
		numDigiHops: 0,
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyTooManyHops(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-10 * time.Minute),
		numDigiHops: 3,
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyTrue(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-10 * time.Minute),
		numDigiHops: 1,
	}
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyWithinDistance(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-10 * time.Minute),
		numDigiHops: 0,
		dlat:        maybe.Just(42.36),
		dlon:        maybe.Just(-71.06),
	}
	// Filter at same location → 0 km apart, well within 50 km.
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Just(42.36), maybe.Just(-71.06), maybe.Just(50.0)))
}

func TestDBWasRecentlyNearbyTooFar(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-10 * time.Minute),
		numDigiHops: 0,
		dlat:        maybe.Just(42.36), // Boston
		dlon:        maybe.Just(-71.06),
	}
	// Filter at Los Angeles, ~4200 km away.
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Just(34.05), maybe.Just(-118.24), maybe.Just(50.0)))
}

func TestDBWasRecentlyNearbyUnknownStationLocationSkipsDistanceCheck(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{ //nolint:exhaustruct_v5
		callsign:    "W1AW",
		lastHeardRF: time.Now().Add(-10 * time.Minute),
		numDigiHops: 0,
		dlat:        maybe.Nothing[float64](),
		dlon:        maybe.Nothing[float64](),
	}
	// Distance filter requested but station location unknown → distance check skipped → true.
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, maybe.Just(42.36), maybe.Just(-71.06), maybe.Just(50.0)))
}

func TestDBWasRecentlyNearbyEmptyRoleSuppressesOutput(t *testing.T) {
	var mdb = New(0)
	assert.False(t, mdb.WasRecentlyNearby("", "UNKNOWN", 60, 2, maybe.Nothing[float64](), maybe.Nothing[float64](), maybe.Nothing[float64]()))
}

func TestDBWasRecentlyNearbyRoleWithDistanceFilter(t *testing.T) {
	var mdb = New(0)
	// Station not in db; the verbose branch with distance parameters should print.
	assert.False(t, mdb.WasRecentlyNearby("addressee", "UNKNOWN", 60, 2, maybe.Just(42.36), maybe.Just(-71.06), maybe.Just(50.0)))
}

// --- SetMSP / GetMSP ---

func TestDBGetMSPUnknownStation(t *testing.T) {
	var mdb = New(0)
	assert.Equal(t, 0, mdb.GetMSP("W1AW"))
}

func TestDBSetMSPUnknownStationDoesNotPanic(t *testing.T) {
	var mdb = New(0)
	mdb.SetMSP("W1AW", 3) // should not panic; prints an error message
}

func TestDBSetThenGetMSP(t *testing.T) {
	var mdb = New(0)
	mdb.db["W1AW"] = &station{callsign: "W1AW"} //nolint:exhaustruct_v5
	mdb.SetMSP("W1AW", 5)
	assert.Equal(t, 5, mdb.GetMSP("W1AW"))
}

func TestDBSetMSPDebugPrintsMessage(t *testing.T) {
	var mdb = New(1)
	mdb.db["W1AW"] = &station{callsign: "W1AW"} //nolint:exhaustruct_v5
	mdb.SetMSP("W1AW", 3)
	assert.Equal(t, 3, mdb.db["W1AW"].msp)
}

func TestDBGetMSPDebugPrintsMessage(t *testing.T) {
	var mdb = New(1)
	mdb.db["W1AW"] = &station{callsign: "W1AW", msp: 7} //nolint:exhaustruct_v5
	assert.Equal(t, 7, mdb.GetMSP("W1AW"))
}
