#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B1200 -k -n 100 -o test12-bpsk.wav
$ATEST -B1200 -k -F0 -L87 -G94 test12-bpsk.wav
$ATEST -B1200 -k -F1 -L90 -G99 test12-bpsk.wav
