#!/bin/bash -e

# shellcheck disable=SC2317
exit 0 # FIXME Need gen_packets with -B EAS support

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B EAS -o testeas.wav
$ATEST -B EAS -L 6 -G 6 testeas.wav
