#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B2400 -J -n 100 -o test24-b.wav

f0() { $ATEST -B2400 -J -F0 -L81 -G88 test24-b.wav; }
f1() { $ATEST -B2400 -J -F1 -L86 -G92 test24-b.wav; }

run_parallel f0 f1
