#!/bin/bash -e

# shellcheck disable=SC2317
exit 0 # FIXME Need gen_packets with -I support

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B9600 -I1 -n 100 -o test96-il2p-I1.wav
$ATEST -B9600 -L72 -G76 test96-il2p-I1.wav
$ATEST -B9600 -P+ -L76 -G80 test96-il2p-I1.wav

$GEN_PACKETS -B9600 -I0 -n 100 -o test96-il2p-I0.wav
$ATEST -B9600 -L64 -G68 test96-il2p-I0.wav


$GEN_PACKETS -B9600 -i1 -n 100 -o test96-il2p-i1.wav
$ATEST -B9600 -L70 -G74 test96-il2p-i1.wav
$ATEST -B9600 -P+ -L73 -G77 test96-il2p-i1.wav

$GEN_PACKETS -B9600 -i0 -n 100 -o test96-il2p-i0.wav
$ATEST -B9600 -L67 -G71 test96-il2p-i0.wav


