#!/bin/bash -e

# shellcheck disable=SC2317
exit 0 # FIXME Need gen_packets with -I support

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -I1 -n 100 -o test12-il2p.wav
$ATEST -P+ -D1 -L92 -G94 test12-il2p.wav
