#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B300 -k -n 100 -o test300-bpsk.wav

f0() { $ATEST -B300 -k -F0 -L78 -G82 test300-bpsk.wav; }
f1() { $ATEST -B300 -k -F1 -L78 -G82 test300-bpsk.wav; }

run_parallel f0 f1
