#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B300 -k -n 100 -o test300-bpsk.wav
$ATEST -B300 -k -F0 -L80 -G88 test300-bpsk.wav
$ATEST -B300 -k -F1 -L81 -G89 test300-bpsk.wav
