#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B2400 -j -n 100 -o test24-a.wav
$ATEST -B2400 -j -F0 -L76 -G85 test24-a.wav
$ATEST -B2400 -j -F1 -L84 -G92 test24-a.wav
