#!/bin/bash -e

source "$(dirname "$(realpath "$0")")/common"

goto_tmpdir

$GEN_PACKETS -B300 -k -I1 -n 100 -o test300-bpsk-il2p.wav
$ATEST -B300 -k -F0 -L87 -G95 test300-bpsk-il2p.wav
$ATEST -B300 -k -F1 -L87 -G95 test300-bpsk-il2p.wav
