#!/bin/bash

ATEST="$(dirname "$(realpath "$0")")/../dist/samoyed-atest"
export ATEST

FXSEND="$(dirname "$(realpath "$0")")/../dist/samoyed-fxsend"
export FXSEND
FXREC="$(dirname "$(realpath "$0")")/../dist/samoyed-fxrec"
export FXREC

GEN_PACKETS="$(dirname "$(realpath "$0")")/../dist/samoyed-gen_packets"
export GEN_PACKETS

function goto_tmpdir() {
	TMPDIR=$(mktemp --directory)
	echo "$TMPDIR"
	cd "$TMPDIR" || exit
}
