// SPDX-FileCopyrightText: 2026 The Samoyed Authors
// SPDX-License-Identifier: GPL-2.0-or-later

package direwolf

import (
	"bytes"
	"testing"

	"github.com/doismellburning/samoyed/internal/maybe"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The expected bytes here are written out by hand from the layouts the Linux
// kernel's nr_write_internal and __nr_transmit_reply and netromd's netromt
// produce, rather than generated by the encoder under test, so that a test
// that passes means we agree with them and not merely with ourselves.

// Seven-byte AX.25 addresses: each character shifted left one bit, space
// padded, then 0x60 | SSID<<1.
func q1test7Addr() []byte { return []byte{0xA2, 0x62, 0xA8, 0x8A, 0xA6, 0xA8, 0x6E} } // Q1TEST-7
func q2test7Addr() []byte { return []byte{0xA2, 0x64, 0xA8, 0x8A, 0xA6, 0xA8, 0x6E} } // Q2TEST-7
func q3test7Addr() []byte { return []byte{0xA2, 0x66, 0xA8, 0x8A, 0xA6, 0xA8, 0x6E} } // Q3TEST-7
func q1testAddr() []byte  { return []byte{0xA2, 0x62, 0xA8, 0x8A, 0xA6, 0xA8, 0x60} } // Q1TEST
func q9Addr() []byte      { return []byte{0xA2, 0x72, 0x40, 0x40, 0x40, 0x40, 0x7E} } // Q9-15

func concat(parts ...[]byte) []byte {
	return bytes.Join(parts, nil)
}

// networkHeader() is Q1TEST-7 to Q2TEST-7 with a TTL of 16.
func networkHeader() []byte {
	return concat(q1test7Addr(), q2test7Addr(), []byte{0x10})
}

// testNetromFrame is a frame with that network header, for circuit 1/2.
func testNetromFrame(op netromOpcode) *netromFrame {
	var f = new(netromFrame)
	f.origin = "Q1TEST-7"
	f.destination = "Q2TEST-7"
	f.ttl = 16
	f.index = 0x01
	f.id = 0x02
	f.opcode = op

	return f
}

func TestNetromCallEncoding(t *testing.T) {
	var testCases = []struct {
		call string
		want []byte
	}{
		{"Q1TEST-7", q1test7Addr()},
		{"Q1TEST", q1testAddr()},
		{"q1test-0", q1testAddr()},
		{"Q9-15", q9Addr()},
	}

	for _, tc := range testCases {
		t.Run(tc.call, func(t *testing.T) {
			var got, err = appendNetromCall(nil, tc.call)
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)

			var decoded, decodeErr = decodeNetromCall(got)
			require.NoError(t, decodeErr)

			var normalised, normErr = normaliseNetromCallsign(tc.call)
			require.NoError(t, normErr)
			assert.Equal(t, normalised, decoded)
		})
	}
}

func TestNetromCallRejects(t *testing.T) {
	for _, call := range []string{"", "Q1TESTX", "Q1-16", "Q1--1", "Q1TEST-A", "Q1_TEST", "-7"} {
		var _, err = appendNetromCall(nil, call)
		require.Error(t, err, "%q should not encode", call)
	}

	var testCases = []struct {
		name string
		addr []byte
	}{
		{"a character after the padding", []byte{0xA2, 0x40, 0xA8, 0x40, 0x40, 0x40, 0x60}},
		{"lowercase", []byte{'q' << 1, 0x40, 0x40, 0x40, 0x40, 0x40, 0x60}},
		{"all padding", []byte{0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x60}},
		{"too short", q1testAddr()[:6]},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var _, err = decodeNetromCall(tc.addr)
			assert.Error(t, err)
		})
	}
}

// The SSID byte's C, E and spare bits say nothing about the callsign.
func TestNetromCallIgnoresAddressFlagBits(t *testing.T) {
	var addr = append([]byte(nil), q1test7Addr()...)
	addr[6] = 0x8F // C and E set, spares clear, SSID 7.

	var got, err = decodeNetromCall(addr)
	require.NoError(t, err)
	assert.Equal(t, "Q1TEST-7", got)
}

func TestNetromConnReq(t *testing.T) {
	var frame = testNetromFrame(netromOpConnReq)
	frame.window = 4
	frame.user = "Q1TEST"
	frame.originNode = "Q1TEST-7"

	var plain = concat(networkHeader(), []byte{0x01, 0x02, 0x00, 0x00, 0x01, 0x04}, q1testAddr(), q1test7Addr())

	t.Run("without the BPQ timeout", func(t *testing.T) {
		assertNetromEncodesTo(t, frame, plain)
		assertNetromDecodesTo(t, plain, frame)
	})

	t.Run("with the BPQ timeout", func(t *testing.T) {
		var withTimeout = *frame
		withTimeout.timeout = maybe.Just(120)

		var want = concat(plain, []byte{0x78, 0x00})
		require.Len(t, want, 37, "Linux recognises the timeout by a length of 37")

		assertNetromEncodesTo(t, &withTimeout, want)
		assertNetromDecodesTo(t, want, &withTimeout)
	})

	t.Run("truncated", func(t *testing.T) {
		var _, err = decodeNetromFrame(plain[:len(plain)-1])
		assert.ErrorIs(t, err, errNetromShort)
	})
}

func TestNetromConnAck(t *testing.T) {
	var frame = testNetromFrame(netromOpConnAck)
	frame.txSeq = 0x05
	frame.rxSeq = 0x06
	frame.window = 4

	var plain = concat(networkHeader(), []byte{0x01, 0x02, 0x05, 0x06, 0x02, 0x04})

	t.Run("plain", func(t *testing.T) {
		assertNetromEncodesTo(t, frame, plain)
		assertNetromDecodesTo(t, plain, frame)

		assert.Equal(t, byte(0x05), frame.peerIndex())
		assert.Equal(t, byte(0x06), frame.peerID())
	})

	t.Run("with the BPQ TTL", func(t *testing.T) {
		var withTTL = *frame
		withTTL.ackTTL = maybe.Just[byte](16)

		var want = concat(plain, []byte{0x10})
		assertNetromEncodesTo(t, &withTTL, want)
		assertNetromDecodesTo(t, want, &withTTL)
	})

	t.Run("an acceptance must carry a window", func(t *testing.T) {
		var _, err = decodeNetromFrame(plain[:netromHeaderLen])
		assert.ErrorIs(t, err, errNetromShort)
	})
}

// A refusal is a CONNECT ACK with the choke flag, as Linux's
// nr_transmit_refusal sends it: the requester's circuit, zeroes, and a single
// zero byte where the window would be.
func TestNetromConnAckRefusal(t *testing.T) {
	var refusal = concat(networkHeader(), []byte{0x01, 0x02, 0x00, 0x00, 0x82, 0x00})

	var f, err = decodeNetromFrame(refusal)
	require.NoError(t, err)
	assert.Equal(t, netromOpConnAck, f.opcode)
	assert.True(t, f.has(netromFlagChoke))

	// Some implementations leave the byte off altogether.
	f, err = decodeNetromFrame(refusal[:netromHeaderLen])
	require.NoError(t, err)
	assert.True(t, f.has(netromFlagChoke))
}

func TestNetromInfo(t *testing.T) {
	var frame = testNetromFrame(netromOpInfo)
	frame.txSeq = 3
	frame.rxSeq = 5
	frame.flags = netromFlagMore
	frame.info = []byte("hi")

	var want = concat(networkHeader(), []byte{0x01, 0x02, 0x03, 0x05, 0x25, 'h', 'i'})
	assertNetromEncodesTo(t, frame, want)
	assertNetromDecodesTo(t, want, frame)
}

func TestNetromShortOpcodes(t *testing.T) {
	var testCases = []struct {
		name   string
		opcode netromOpcode
		flags  byte
		rxSeq  byte
		tail   []byte
	}{
		{"INFO ACK with NAK and CHOKE", netromOpInfoAck, netromFlagNAK | netromFlagChoke, 9, []byte{0x01, 0x02, 0x00, 0x09, 0xC6}},
		{"DISC REQ", netromOpDiscReq, 0, 0, []byte{0x01, 0x02, 0x00, 0x00, 0x03}},
		{"DISC ACK", netromOpDiscAck, 0, 0, []byte{0x01, 0x02, 0x00, 0x00, 0x04}},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var frame = testNetromFrame(tc.opcode)
			frame.flags = tc.flags
			frame.rxSeq = tc.rxSeq

			var want = concat(networkHeader(), tc.tail)
			assertNetromEncodesTo(t, frame, want)
			assertNetromDecodesTo(t, want, frame)
		})
	}
}

// Xrouter's "reset" (opcode 7) and anything else unassigned is not ours to
// interpret.
func TestNetromUnknownOpcode(t *testing.T) {
	var _, err = decodeNetromFrame(concat(networkHeader(), []byte{0x01, 0x02, 0x00, 0x00, 0x07}))
	assert.Error(t, err)
}

func TestNetromNodes(t *testing.T) {
	var want = concat(
		[]byte{0xFF}, []byte("QNODEA"),
		q2test7Addr(), []byte("QNODEB"), q2test7Addr(), []byte{200},
		q3test7Addr(), []byte("QC    "), q2test7Addr(), []byte{150},
	)

	var entries = []netromNodesEntry{
		{callsign: "Q2TEST-7", alias: "QNODEB", neighbour: "Q2TEST-7", quality: 200},
		{callsign: "Q3TEST-7", alias: "QC", neighbour: "Q2TEST-7", quality: 150},
	}

	var frames, err = encodeNetromNodes("QNODEA", entries)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	assert.Equal(t, want, frames[0])

	var nodes, decodeErr = decodeNetromNodes(want)
	require.NoError(t, decodeErr)
	assert.Equal(t, "QNODEA", nodes.alias)
	assert.Equal(t, entries, nodes.entries)
}

// With nothing to advertise, the broadcast is still sent: the header alone is
// how a node's neighbours learn it is there.
func TestNetromNodesHeaderOnly(t *testing.T) {
	var frames, err = encodeNetromNodes("QNODEA", nil)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	assert.Equal(t, concat([]byte{0xFF}, []byte("QNODEA")), frames[0])
}

// A big table goes out over several frames, none of them past netromd's 256
// bytes, rather than one frame truncated part way through an entry.
func TestNetromNodesSplitsIntoFrames(t *testing.T) {
	var entries = make([]netromNodesEntry, 23)
	for i := range entries {
		entries[i] = netromNodesEntry{callsign: "Q2TEST-7", alias: "QNODEB", neighbour: "Q2TEST-7", quality: byte(i)}
	}

	var frames, err = encodeNetromNodes("QNODEA", entries)
	require.NoError(t, err)
	require.Len(t, frames, 3)

	var got []netromNodesEntry

	for _, frame := range frames {
		assert.LessOrEqual(t, len(frame), 256)

		var nodes, decodeErr = decodeNetromNodes(frame)
		require.NoError(t, decodeErr)
		got = append(got, nodes.entries...)
	}

	assert.Equal(t, entries, got)
}

func TestNetromNodesDecoding(t *testing.T) {
	var good = concat(q2test7Addr(), []byte("QNODEB"), q2test7Addr(), []byte{200})

	t.Run("the signature is required", func(t *testing.T) {
		var _, err = decodeNetromNodes(concat([]byte{0x00}, []byte("QNODEA"), good))
		assert.Error(t, err)
	})

	t.Run("an alias ends at a space or NUL", func(t *testing.T) {
		var nodes, err = decodeNetromNodes(concat([]byte{0xFF}, []byte("AB C\x00\x00")))
		require.NoError(t, err)
		assert.Equal(t, "AB", nodes.alias)
	})

	t.Run("an invalid entry is skipped, not the rest", func(t *testing.T) {
		var bad = concat(q2test7Addr(), []byte("QN!DEB"), q2test7Addr(), []byte{200})

		var nodes, err = decodeNetromNodes(concat([]byte{0xFF}, []byte("QNODEA"), bad, good))
		require.NoError(t, err)
		require.Len(t, nodes.entries, 1)
		assert.Equal(t, "QNODEB", nodes.entries[0].alias)
	})

	t.Run("a partial trailing entry is ignored", func(t *testing.T) {
		var nodes, err = decodeNetromNodes(concat([]byte{0xFF}, []byte("QNODEA"), good, good[:10]))
		require.NoError(t, err)
		assert.Len(t, nodes.entries, 1)
	})
}

func TestNetromAliasRejects(t *testing.T) {
	for _, alias := range []string{"TOOLONG", "A B", "A!"} {
		var _, err = appendNetromAlias(nil, alias)
		require.Error(t, err, "%q should not encode", alias)
	}
}

func assertNetromEncodesTo(t *testing.T, f *netromFrame, want []byte) {
	t.Helper()

	var got, err = f.encode()
	require.NoError(t, err)
	assert.Equal(t, want, got)
}

func assertNetromDecodesTo(t *testing.T, b []byte, want *netromFrame) {
	t.Helper()

	var got, err = decodeNetromFrame(b)
	require.NoError(t, err)
	assert.Equal(t, want, got)
}
