package direwolf

// KG 2026-07-26 These tests were generated by Claude based on gen_tone.go
// and as such it's very much a test of the implementation as-is.
// A failing test may thus be a problem with the test itself rather than any future changes...

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func newTestAudioConfig(channel int, modemType modem_t, baud int, markFreq int, spaceFreq int, samplesPerSec int) *audio_s {
	var audioConfig audio_s

	audioConfig.chan_medium[channel] = MEDIUM_RADIO
	audioConfig.achan[channel].modem_type = modemType
	audioConfig.achan[channel].baud = baud
	audioConfig.achan[channel].mark_freq = markFreq
	audioConfig.achan[channel].space_freq = spaceFreq
	audioConfig.adev[ACHAN2ADEV(channel)].samples_per_sec = samplesPerSec
	audioConfig.adev[ACHAN2ADEV(channel)].num_channels = 1
	audioConfig.adev[ACHAN2ADEV(channel)].bits_per_sample = 16

	return &audioConfig
}

func TestNewToneGeneratorAFSK(t *testing.T) {
	var channel = 0
	var baud = 1200
	var markFreq = 1200
	var spaceFreq = 2200
	var samplesPerSec = 44100
	var audioConfig = newTestAudioConfig(channel, MODEM_AFSK, baud, markFreq, spaceFreq, samplesPerSec)

	var tg = NewToneGenerator(channel, audioConfig)

	require.NotNil(t, tg)
	assert.Equal(t, channel, tg.channel)
	assert.Equal(t, ACHAN2ADEV(channel), tg.adevIndex)
	assert.Equal(t, int((TICKS_PER_CYCLE/float64(samplesPerSec))+0.5), tg.ticksPerSample)
	assert.Equal(t, int((TICKS_PER_CYCLE/float64(baud))+0.5), tg.ticksPerBit)
	assert.Equal(t, uint((float64(markFreq)*TICKS_PER_CYCLE/float64(samplesPerSec))+0.5), tg.f1ChangePerSample)
	assert.Equal(t, uint((float64(spaceFreq)*TICKS_PER_CYCLE/float64(samplesPerSec))+0.5), tg.f2ChangePerSample)
	assert.InDelta(t, float64(samplesPerSec)/float64(baud), tg.samplesPerSymbol, 0.0001)
}

func TestNewToneGeneratorBPSK(t *testing.T) {
	var channel = 0
	var audioConfig = newTestAudioConfig(channel, MODEM_BPSK, 2400, 0, 0, 44100)

	var tg = NewToneGenerator(channel, audioConfig)

	require.NotNil(t, tg)
	// BPSK forces mark_freq to 1800 and mirrors it into space_freq.
	assert.Equal(t, 1800, audioConfig.achan[channel].mark_freq)
	assert.Equal(t, 1800, audioConfig.achan[channel].space_freq)
	assert.Equal(t, tg.f1ChangePerSample, tg.f2ChangePerSample)
	assert.Equal(t, PHASE_SHIFT_45, tg.tonePhase)
}

func TestToneGeneratorsAreIndependentPerChannel(t *testing.T) {
	var chan0 = 0
	var chan1 = 1
	var audioConfig = newTestAudioConfig(chan0, MODEM_AFSK, 1200, 1200, 2200, 44100)
	audioConfig.chan_medium[chan1] = MEDIUM_RADIO
	audioConfig.achan[chan1].modem_type = MODEM_AFSK
	audioConfig.achan[chan1].baud = 9600
	audioConfig.achan[chan1].mark_freq = 1200
	audioConfig.achan[chan1].space_freq = 2200

	var tg0 = NewToneGenerator(chan0, audioConfig)
	var tg1 = NewToneGenerator(chan1, audioConfig)

	// Mutating one channel's accumulator directly (rather than going through
	// PutBit, which requires a live audio device) confirms the two instances
	// don't share backing storage.
	tg0.bitLenAcc = 42

	assert.NotEqual(t, tg0.ticksPerBit, tg1.ticksPerBit)
	assert.Equal(t, 42, tg0.bitLenAcc)
	assert.Zero(t, tg1.bitLenAcc)
}
