package direwolf

const IL2P_PREAMBLE = 0x55

const IL2P_SYNC_WORD = 0xF15E48

const IL2P_SYNC_WORD_SIZE = 3
const IL2P_HEADER_SIZE = 13 // Does not include 2 parity.
const IL2P_HEADER_PARITY = 2

const IL2P_MAX_PAYLOAD_SIZE = 1023
const IL2P_MAX_PAYLOAD_BLOCKS = 5
const IL2P_MAX_PARITY_SYMBOLS = 16 // For payload only.
const IL2P_MAX_ENCODED_PAYLOAD_SIZE = (IL2P_MAX_PAYLOAD_SIZE + IL2P_MAX_PAYLOAD_BLOCKS*IL2P_MAX_PARITY_SYMBOLS)

const IL2P_CRC_ENCODED_SIZE = 4 // 16-bit CRC -> 4 Hamming-encoded bytes

const IL2P_MAX_PACKET_SIZE = (IL2P_SYNC_WORD_SIZE + IL2P_HEADER_SIZE + IL2P_HEADER_PARITY + IL2P_MAX_ENCODED_PAYLOAD_SIZE + IL2P_CRC_ENCODED_SIZE)
