package direwolf

// KG 2026-03-07 These tests were generated by Claude based on mheard.go
// and as such it's very much a test of the implementation as-is.
// A failing test may thus be a problem with the test itself rather than any future changes...

import (
	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- mheard_age ---

func TestMheardAge(t *testing.T) {
	var now = time.Now()

	t.Run("zero time returns placeholder", func(t *testing.T) {
		assert.Equal(t, "-  ", mheard_age(now, time.Time{}))
	})

	t.Run("90 minutes ago", func(t *testing.T) {
		assert.Equal(t, "   1:30", mheard_age(now, now.Add(-90*time.Minute)))
	})

	t.Run("5 minutes ago", func(t *testing.T) {
		assert.Equal(t, "   0:05", mheard_age(now, now.Add(-5*time.Minute)))
	})

	t.Run("same moment", func(t *testing.T) {
		assert.Equal(t, "   0:00", mheard_age(now, now))
	})
}

// --- mheard_latlon ---

func TestMheardLatlon(t *testing.T) {
	t.Run("both unknown", func(t *testing.T) {
		assert.Equal(t, "   -       -  ", mheard_latlon(G_UNKNOWN, G_UNKNOWN))
	})

	t.Run("lat unknown lon known", func(t *testing.T) {
		assert.Equal(t, "   -       -  ", mheard_latlon(G_UNKNOWN, -71.0))
	})

	t.Run("lat known lon unknown", func(t *testing.T) {
		assert.Equal(t, "   -       -  ", mheard_latlon(42.0, G_UNKNOWN))
	})

	t.Run("both known", func(t *testing.T) {
		var expected = fmt.Sprintf("%6.2f %7.2f", 42.36, -71.06)
		assert.Equal(t, expected, mheard_latlon(42.36, -71.06))
	})
}

// --- NewMHeardDB ---

func TestNewMHeardDB(t *testing.T) {
	var mdb = NewMHeardDB(3)
	require.NotNil(t, mdb)
	assert.Equal(t, 3, mdb.debug)
	assert.NotNil(t, mdb.db)
	assert.Empty(t, mdb.db)
}

// --- Count ---

func TestMHeardDBCount(t *testing.T) {
	var now = time.Now()

	t.Run("empty db", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		assert.Equal(t, 0, mdb.Count(0, 60))
	})

	t.Run("station heard directly counted", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
			callsign:      "W1AW",
			last_heard_rf: now.Add(-10 * time.Minute),
			num_digi_hops: 0,
		}
		assert.Equal(t, 1, mdb.Count(0, 60))
	})

	t.Run("station excluded by max hops", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		mdb.db["W2AW"] = &mheard_t{ //nolint:exhaustruct
			callsign:      "W2AW",
			last_heard_rf: now.Add(-5 * time.Minute),
			num_digi_hops: 3,
		}
		assert.Equal(t, 0, mdb.Count(2, 60))
	})

	t.Run("IS-only station not counted", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		mdb.db["IS1"] = &mheard_t{ //nolint:exhaustruct
			callsign:      "IS1",
			last_heard_is: now.Add(-5 * time.Minute),
		}
		assert.Equal(t, 0, mdb.Count(8, 60))
	})

	t.Run("old RF station excluded by time limit", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		mdb.db["OLD"] = &mheard_t{ //nolint:exhaustruct
			callsign:      "OLD",
			last_heard_rf: now.Add(-120 * time.Minute),
			num_digi_hops: 0,
		}
		assert.Equal(t, 0, mdb.Count(0, 60))
	})

	t.Run("multiple stations counted correctly", func(t *testing.T) {
		var mdb = NewMHeardDB(0)
		mdb.db["A"] = &mheard_t{last_heard_rf: now.Add(-5 * time.Minute), num_digi_hops: 0}  //nolint:exhaustruct
		mdb.db["B"] = &mheard_t{last_heard_rf: now.Add(-10 * time.Minute), num_digi_hops: 1} //nolint:exhaustruct
		mdb.db["C"] = &mheard_t{last_heard_rf: now.Add(-10 * time.Minute), num_digi_hops: 3} //nolint:exhaustruct
		mdb.db["D"] = &mheard_t{last_heard_is: now.Add(-5 * time.Minute)}                    //nolint:exhaustruct
		assert.Equal(t, 2, mdb.Count(2, 60))
	})

	t.Run("debug mode prints message", func(t *testing.T) {
		var mdb = NewMHeardDB(1)
		mdb.db["X"] = &mheard_t{last_heard_rf: now.Add(-5 * time.Minute), num_digi_hops: 0} //nolint:exhaustruct
		assert.Equal(t, 1, mdb.Count(0, 60))
	})
}

// --- SaveRF helpers ---

var saveRFAlevel = alevel_t{}                                     //nolint:exhaustruct
var saveRFNoPos = &decode_aprs_t{g_packet_type: packet_type_none} //nolint:exhaustruct
var saveRFWithPos = &decode_aprs_t{                               //nolint:exhaustruct
	g_packet_type: packet_type_position,
	g_lat:         42.36,
	g_lon:         -71.06,
}
var saveRFWithPosUnknown = &decode_aprs_t{ //nolint:exhaustruct
	g_packet_type: packet_type_position,
	g_lat:         G_UNKNOWN,
	g_lon:         G_UNKNOWN,
}

// --- SaveRF ---

func TestMHeardDBSaveRFNewStation(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var pp = ax25_from_text("W1AW>APRS:test", true)

	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)

	require.Contains(t, mdb.db, "W1AW")
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.Equal(t, 0, mdb.db["W1AW"].num_digi_hops)
	assert.Equal(t, 0, mdb.db["W1AW"].channel)
	assert.InDelta(t, float64(G_UNKNOWN), mdb.db["W1AW"].dlat, 0.001)
	assert.InDelta(t, float64(G_UNKNOWN), mdb.db["W1AW"].dlon, 0.001)
}

func TestMHeardDBSaveRFPositionSaved(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var pp = ax25_from_text("W1AW>APRS:test", true)

	mdb.SaveRF(0, saveRFWithPos, pp, saveRFAlevel, RETRY_NONE)

	require.Contains(t, mdb.db, "W1AW")
	assert.InDelta(t, 42.36, mdb.db["W1AW"].dlat, 0.001)
	assert.InDelta(t, -71.06, mdb.db["W1AW"].dlon, 0.001)
}

func TestMHeardDBSaveRFPositionNotSavedForNonPositionPacket(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var pp = ax25_from_text("W1AW>APRS:test", true)

	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)

	assert.InDelta(t, float64(G_UNKNOWN), mdb.db["W1AW"].dlat, 0.001)
}

func TestMHeardDBSaveRFUnknownPositionNotSaved(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var pp = ax25_from_text("W1AW>APRS:test", true)

	mdb.SaveRF(0, saveRFWithPosUnknown, pp, saveRFAlevel, RETRY_NONE)

	assert.InDelta(t, float64(G_UNKNOWN), mdb.db["W1AW"].dlat, 0.001)
}

func TestMHeardDBSaveRFExistingStationUpdated(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var pp = ax25_from_text("W1AW>APRS:test", true)

	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
	// Push the last-heard time back so the 15-second same-transmission guard doesn't fire.
	mdb.db["W1AW"].last_heard_rf = time.Now().Add(-30 * time.Second)
	mdb.SaveRF(1, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)

	assert.Equal(t, 2, mdb.db["W1AW"].count)
	assert.Equal(t, 1, mdb.db["W1AW"].channel)
}

func TestMHeardDBSaveRFHigherHopSkippedWithin15s(t *testing.T) {
	var mdb = NewMHeardDB(0)

	// First: heard directly (0 hops).
	var ppDirect = ax25_from_text("W1AW>APRS:test", true)
	mdb.SaveRF(0, saveRFNoPos, ppDirect, saveRFAlevel, RETRY_NONE)
	assert.Equal(t, 0, mdb.db["W1AW"].num_digi_hops)

	// Second: heard via one digipeater, but within 15 seconds of the first.
	var ppVia = ax25_from_text("W1AW>APRS,RELAY*:test", true)
	mdb.SaveRF(0, saveRFNoPos, ppVia, saveRFAlevel, RETRY_NONE)

	// Should stay at 1 count and 0 hops (the higher-hop copy is ignored).
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.Equal(t, 0, mdb.db["W1AW"].num_digi_hops)
}

func TestMHeardDBSaveRFWideHopHackReducesCount(t *testing.T) {
	var mdb = NewMHeardDB(0)
	// W3AW* (used, len 4 – not WIDE) then WIDE2* (used, len 5, WIDE prefix, ssid 0).
	// Raw hops = 2, hack reduces by one → hops = 1.
	var pp = ax25_from_text("W1AW>APRS,W3AW*,WIDE2*:test", true)

	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)

	assert.Equal(t, 1, mdb.db["W1AW"].num_digi_hops)
}

func TestMHeardDBSaveRFWideHackIgnoresNonZeroSsid(t *testing.T) {
	var mdb = NewMHeardDB(0)
	// WIDE1-1 has ssid 1, so the hack must not fire.
	// Raw hops = 2 and nothing should be reduced.
	var pp = ax25_from_text("W1AW>APRS,W3AW*,WIDE1-1*:test", true)

	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)

	assert.Equal(t, 2, mdb.db["W1AW"].num_digi_hops)
}

func TestMHeardDBSaveRFDebug1SkipBranch(t *testing.T) {
	// debug=1 + higher-hop copy within 15 s → exercises the "skip" debug message.
	var mdb = NewMHeardDB(1)
	var ppDirect = ax25_from_text("W1AW>APRS:test", true)
	mdb.SaveRF(0, saveRFNoPos, ppDirect, saveRFAlevel, RETRY_NONE)

	var ppVia = ax25_from_text("W1AW>APRS,RELAY*:test", true)
	mdb.SaveRF(0, saveRFNoPos, ppVia, saveRFAlevel, RETRY_NONE)
}

func TestMHeardDBSaveRFDebug1UpdateBranch(t *testing.T) {
	// debug=1 + update after >15 s → exercises the "update time" debug message.
	var mdb = NewMHeardDB(1)
	var pp = ax25_from_text("W1AW>APRS:test", true)
	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
	mdb.db["W1AW"].last_heard_rf = time.Now().Add(-30 * time.Second)
	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
}

func TestMHeardDBSaveRFDebug1TriggersDump(t *testing.T) {
	var mdb = NewMHeardDB(1)
	var pp = ax25_from_text("W1AW>APRS:test", true)
	// Must not panic; dump is triggered by debug > 0.
	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
}

func TestMHeardDBSaveRFDebug2PrintsCountAndDump(t *testing.T) {
	var mdb = NewMHeardDB(2)
	var pp = ax25_from_text("W1AW>APRS:test", true)
	// Must not panic; both the count debug line and dump are triggered.
	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
}

// --- dump sort coverage ---

// TestMHeardDBDumpSortIsAfterRf calls dump directly with stations whose IS
// timestamp is newer than their RF timestamp, guaranteeing the
// "ta = ma.last_heard_is" branch inside the sort comparator is reached.
func TestMHeardDBDumpSortIsAfterRf(t *testing.T) {
	var mdb = NewMHeardDB(0)
	var now = time.Now()

	for i, key := range []string{"AA", "BB", "CC", "DD", "EE"} {
		mdb.db[key] = &mheard_t{ //nolint:exhaustruct
			callsign:      key,
			last_heard_rf: now.Add(-time.Duration(60-i*10) * time.Minute),
			last_heard_is: now.Add(-time.Duration(i*5) * time.Minute),
		}
	}

	mdb.dump()
}

// TestMHeardDBDumpSort exercises the sort comparison function inside dump via
// SaveRF with debug=1.  The stations have deliberately varied timestamps so
// that all three comparison outcomes (before / after / equal) are reached.
func TestMHeardDBDumpSort(t *testing.T) {
	var mdb = NewMHeardDB(1)
	var now = time.Now()
	var sameTime = now.Add(-20 * time.Minute)

	// Two stations with identical effective time → equal comparison (return 0).
	mdb.db["EQ1"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "EQ1",
		last_heard_rf: sameTime,
	}
	mdb.db["EQ2"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "EQ2",
		last_heard_rf: sameTime,
	}
	// A station whose IS time is more recent than its RF time, exercising the
	// "use IS time" branch inside the comparator.
	mdb.db["ISLATE"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "ISLATE",
		last_heard_rf: now.Add(-30 * time.Minute),
		last_heard_is: now.Add(-5 * time.Minute),
	}
	// An older station to ensure at least one before/after comparison.
	mdb.db["OLD"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "OLD",
		last_heard_rf: now.Add(-60 * time.Minute),
	}

	// Trigger dump via SaveRF.
	var pp = ax25_from_text("W1AW>APRS:test", true)
	mdb.SaveRF(0, saveRFNoPos, pp, saveRFAlevel, RETRY_NONE)
}

// --- SaveIS ---

func TestMHeardDBSaveISNewStation(t *testing.T) {
	var mdb = NewMHeardDB(0)

	mdb.SaveIS("W1AW>APRS,TCPIP*,qAC,T2SERVER:test")

	require.Contains(t, mdb.db, "W1AW")
	assert.Equal(t, 1, mdb.db["W1AW"].count)
	assert.False(t, mdb.db["W1AW"].last_heard_is.IsZero())
}

func TestMHeardDBSaveISExistingStationUpdated(t *testing.T) {
	var mdb = NewMHeardDB(0)

	mdb.SaveIS("W1AW>APRS:first")
	mdb.SaveIS("W1AW>APRS:second")

	assert.Equal(t, 2, mdb.db["W1AW"].count)
}

func TestMHeardDBSaveISDebug1(t *testing.T) {
	var mdb = NewMHeardDB(1)
	// Exercises both the "added new" and "update time" debug paths.
	mdb.SaveIS("W1AW>APRS:test1")
	mdb.SaveIS("W1AW>APRS:test2")
}

func TestMHeardDBSaveISDebug2(t *testing.T) {
	var mdb = NewMHeardDB(2)
	mdb.SaveIS("W1AW>APRS:test")
}

// --- WasRecentlyNearby ---

func TestMHeardDBWasRecentlyNearbyUnknownStation(t *testing.T) {
	var mdb = NewMHeardDB(0)
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyISOnlyStation(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_is: time.Now(),
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyTooLongAgo(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-120 * time.Minute),
		num_digi_hops: 0,
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyTooManyHops(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-10 * time.Minute),
		num_digi_hops: 3,
	}
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyTrue(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-10 * time.Minute),
		num_digi_hops: 1,
	}
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyWithinDistance(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-10 * time.Minute),
		num_digi_hops: 0,
		dlat:          42.36,
		dlon:          -71.06,
	}
	// Filter at same location → 0 km apart, well within 50 km.
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, 42.36, -71.06, 50.0))
}

func TestMHeardDBWasRecentlyNearbyTooFar(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-10 * time.Minute),
		num_digi_hops: 0,
		dlat:          42.36, // Boston
		dlon:          -71.06,
	}
	// Filter at Los Angeles, ~4200 km away.
	assert.False(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, 34.05, -118.24, 50.0))
}

func TestMHeardDBWasRecentlyNearbyUnknownStationLocationSkipsDistanceCheck(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{ //nolint:exhaustruct
		callsign:      "W1AW",
		last_heard_rf: time.Now().Add(-10 * time.Minute),
		num_digi_hops: 0,
		dlat:          G_UNKNOWN,
		dlon:          G_UNKNOWN,
	}
	// Distance filter requested but station location unknown → distance check skipped → true.
	assert.True(t, mdb.WasRecentlyNearby("addressee", "W1AW", 60, 2, 42.36, -71.06, 50.0))
}

func TestMHeardDBWasRecentlyNearbyEmptyRoleSuppressesOutput(t *testing.T) {
	var mdb = NewMHeardDB(0)
	assert.False(t, mdb.WasRecentlyNearby("", "UNKNOWN", 60, 2, G_UNKNOWN, G_UNKNOWN, G_UNKNOWN))
}

func TestMHeardDBWasRecentlyNearbyRoleWithDistanceFilter(t *testing.T) {
	var mdb = NewMHeardDB(0)
	// Station not in db; the verbose branch with distance parameters should print.
	assert.False(t, mdb.WasRecentlyNearby("addressee", "UNKNOWN", 60, 2, 42.36, -71.06, 50.0))
}

// --- SetMSP / GetMSP ---

func TestMHeardDBGetMSPUnknownStation(t *testing.T) {
	var mdb = NewMHeardDB(0)
	assert.Equal(t, 0, mdb.GetMSP("W1AW"))
}

func TestMHeardDBSetMSPUnknownStationDoesNotPanic(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.SetMSP("W1AW", 3) // should not panic; prints an error message
}

func TestMHeardDBSetThenGetMSP(t *testing.T) {
	var mdb = NewMHeardDB(0)
	mdb.db["W1AW"] = &mheard_t{callsign: "W1AW"} //nolint:exhaustruct
	mdb.SetMSP("W1AW", 5)
	assert.Equal(t, 5, mdb.GetMSP("W1AW"))
}

func TestMHeardDBSetMSPDebugPrintsMessage(t *testing.T) {
	var mdb = NewMHeardDB(1)
	mdb.db["W1AW"] = &mheard_t{callsign: "W1AW"} //nolint:exhaustruct
	mdb.SetMSP("W1AW", 3)
	assert.Equal(t, 3, mdb.db["W1AW"].msp)
}

func TestMHeardDBGetMSPDebugPrintsMessage(t *testing.T) {
	var mdb = NewMHeardDB(1)
	mdb.db["W1AW"] = &mheard_t{callsign: "W1AW", msp: 7} //nolint:exhaustruct
	assert.Equal(t, 7, mdb.GetMSP("W1AW"))
}
