name: 'build direwolf'

on:
  # permit to manually trigger the CI
  workflow_dispatch:
    inputs:
      cmake_flags:
        description: 'Custom CMAKE flags'
        required: false
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: 'Ubuntu latest Debug',
              os: ubuntu-latest,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'x86_64',
              build_type: 'Debug',
              cmake_extra_flags: ''
            }
          - {
              name: 'Ubuntu 22.04',
              os: ubuntu-22.04,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'x86_64',
              build_type: 'Release',
              cmake_extra_flags: ''
            }

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 8
      - name: dependency
        shell: bash
        run: |
          # this is not perfect but enought for now
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install libasound2-dev libudev-dev libhamlib-dev gpsd
          elif [ "$RUNNER_OS" == "macOS" ]; then
            # just to simplify I use homebrew but
            # we can use macports (latest direwolf is already available as port)
            brew install portaudio hamlib gpsd hidapi
          elif [ "$RUNNER_OS" == "Windows" ]; then
            # add the folder to PATH
            echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
          fi
      - name: create build environment
        run: |
          cmake -E make_directory ${{github.workspace}}/build
      - name: configure
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export CC=${{ matrix.config.cc }}
            export CXX=${{ matrix.config.cxx }}
            export AR=${{ matrix.config.ar }}
            export WINDRES=${{ matrix.config.windres }}
          fi
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_CXX_FLAGS="-Werror" -DUNITTEST=1 \
            ${{ matrix.config.cmake_extra_flags }} \
            ${{ github.event.inputs.cmake_flags }}
      - name: build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export CC=${{ matrix.config.cc }}
            export CXX=${{ matrix.config.cxx }}
            export AR=${{ matrix.config.ar }}
            export WINDRES=${{ matrix.config.windres }}
          fi
          cmake --build . --config ${{ matrix.config.build_type }} \
            ${{ github.event.inputs.cmake_flags }}
      - name: test
        continue-on-error: true
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{ matrix.config.build_type }} \
            --parallel 2 --output-on-failure \
            ${{ github.event.inputs.cmake_flags }}
      - name: package
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" == "Windows" ] ||  [ "$RUNNER_OS" == "macOS" ]; then
            make package
          fi
